#!/usr/bin/env bash
# This script groups Apache log data by IP and HTTP status code, and displays the sorted results

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn | awk '{ print $1 " " $2 " " $3 }'
