#!/usr/bin/env bash
# Script to configure and start Apache in a Docker container for holbertonschool/265-0

# Add the server name configuration to prevent potential warnings
echo "ServerName localhost" >> /etc/apache2/apache2.conf

# Start the Apache service
service apache2 start
