#!/usr/bin/env bash
# Configures Nginx to run as nginx user on port 8080
pkill apache2
chmod 777 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
chown -R nginx:nginx /var/lib/nginx /var/log/nginx /run/nginx.pid
sudo -u nginx service nginx restart
