#!/usr/bin/env bash

# Ensure Nginx runs as the 'nginx' user
sed -i 's/user  nobody;/user nginx;/' /etc/nginx/nginx.conf

# Change the listening port to 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-enabled/default
sed -i 's/listen [::]:80 default_server;/listen [::]:8080 default_server;/' /etc/nginx/sites-enabled/default

# Restart Nginx
sudo systemctl restart nginx
