#!/usr/bin/env bash
# Configures Nginx to run as nginx user on port 8080
pkill apache2
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
chmod 644 /etc/nginx/sites-available/default
sudo -u nginx nginx -t && sudo -u nginx nginx
